version: "3.8"

networks:
  my-network:
    driver: bridge

services:
  user_postgres:
    image: postgres:latest
    container_name: user_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network

  catalog_postgres:
    image: postgres:latest
    container_name: catalog_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalog_db
    ports:
      - "5432:5432"
    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    networks:
      - my-network

  ms-users:
    build:
      context: ./ms-users
    container_name: ms-users
    depends_on:
      - user_postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgres://myuser:mypassword@user_postgres:5432/users_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3000:3000"
    restart: always
    networks:
      - my-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h user_postgres -p 5432 -U myuser"]
      interval: 10s
      retries: 5

  ms-catalog:
    build:
      context: ./ms-catalog
    container_name: ms-catalog
    depends_on:
      - catalog_postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgres://postgres:password@catalog_postgres:5432/catalog_db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "8080:8080"
    restart: always
    networks:
      - my-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - ms-users
      - ms-catalog
    ports:
      - "4000:4000"
    restart: always
    networks:
      - my-network

volumes:
  user_postgres_data:
    driver: local
  catalog_postgres_data:
    driver: local
